# General Configuration
general:
  # Plugin prefix, practically used in every single command
  prefix: "<gold>[<red><bold>Toms3<gray>Core</gray></bold></red>]"
  # Discord Webhook for /dupe Hall of Shame
  # Set it empty to disable
  discord-webhook: ""
  # Spanish translations
  # THIS IS ONLY FOR toms3.cc, MOST MESSAGES CANNOT BE CUSTOMIZED!!!
  # This will be removed soon.
  enable-spanish-translation: false

# Configuration of custom commands + messages
commands:
  # Regex for username validation (/jd, /pt & /ls)
  # Do not change unless your server supports bedrock users or other custom names
  username-validation-regex: "^[a-zA-Z0-9_]{3,16}$"
  # Troll Dupe command (/dupe)
  # le popbob coming for you!!!1111
  dupe:
    # Message sent to the discord webhook
    discord-webhook-message: "%username% is probably missing a lot of neurons"


# Chunk Block Limits
chunk-limits:
  enable: true
  # Currently only limits all kind of chests + shulker boxes
  tile-entities: 250

# Anti illegals system
illegals:
  enable: true
  # Prevents use, also patches dispenser bypass
  prevent-use:
    - SPAWN_EGG
  # Prevents place, only put blocks in there
  prevent-place:
    - BEDROCK
    - SPAWNER

# Other
misc:
  # Join motd, inspired by lsd2.org
  join-motd:
    first-join:
      en: "Welcome to the server!"
      es: "¡Bienvenido al servidor!"
    general:
      en: "Welcome back to the server!"
      es: "¡Bienvenido devuelta al servidor!"
  # Join title
  join-title-message:
    en: "Welcome"
    es: "Bienvenido"
  # Simple announcements system, create as many as you want
  announcements:
    timer: 10
    messages:
      example:
        en: "<gold>Example."
        es: "<gold>Ejemplo."
      example-two:
        en: "<gold>Example two."
        es: "<gold>Ejemplo dos."

# Do not touch.
config-version: 3