# General Configuration
general:
  # Plugin prefix, practically used in every single command
  prefix: "<gold>[<red><bold>Toms3<gray>Core</gray></bold></red>]"
  # Discord Webhook for /dupe Hall of Shame
  # Set it empty to disable
  discord-webhook: ""
  # Spanish translations
  # THIS IS ONLY FOR toms3.cc, MOST MESSAGES CANNOT BE CUSTOMIZED!!!
  # This will be removed soon and replaced with locale-based messages.
  enable-spanish-translation: false
  # Enable cache system logging (logs playerdata creation & last seen updates)
  # Can be annoying if you have a lot of players, so be careful
  # By default, this is set to true
  enable-cache-system-logging: true

# Configuration of custom commands + messages
commands:
  # Regex for username validation (/jd, /pt & /ls)
  # Do not change unless your server supports bedrock users or other custom names
  username-validation-regex: "^[a-zA-Z0-9_]{3,16}$"
  # Troll Dupe command (/dupe)
  # le popbob coming for you!!!1111
  dupe:
    # Message sent to the discord webhook
    discord-webhook-message: "%username% is probably missing a lot of neurons"
  # Vote command (/vote)
  # Has no actual use.
  vote:
    message:
      en: "You can vote the server via: <b>url</b>"
      es: "Puedes votar por el servidor entrando a: <b>url</b>"
  toggleannouncements:
    message:
      "on":
        en: "Announcements are now <b>ON</b>."
        es: "Los anuncios ahora están <b>activados</b>."
      "off":
        en: "Announcements are now <b>OFF</b>."
        es: "Los anuncios ahora están <b>desactivados</b>."

# Utilities that may be useful
utilities:
  # Prevents operators from using certain commands
  # Can be useful when needed
  op-command-blacklist:
    enable: false
    blacklisted-commands:
      - "ban"
      - "minecraft:ban"


# Chunk Block Limits
chunk-limits:
  enable: true
  tile-entities:
    # Logs when the tile entity limit is exceeded (includes name, coords, world & region name)
    # Useful to log any possible chunk bans, but it may be really annoying
    # Recommended to be set to false
    log: false
    entity-limit: 250

# Anti illegals system
illegals:
  # Prevents use of certain items, also patches dispenser bypass
  block-use:
    enable: true
    list:
      - SPAWN_EGG
  # Prevents place, only put blocks in there
  block-place:
    enable: true
    list:
      - BEDROCK
      - SPAWNER
  # Prevents and deletes nbt chests
  # Checks are really strict as it also checks shulkers, it may slightly hurt performance!!
  # You shouldn't enable this unless your server suffers from illegals / admin abuse
  # NBT Chests were used in toms3.cc to crash the whole server by spamming and breaking them
  block-nbt-chests:
    enable: false

# Patches
patches:
  nether:
    # Set it to false if you want to disable the listener completely
    enable: true
    # Blocks nether roof from being accessed. Players get teleported seven blocks below.
    block-nether-roof:
      enable: true
    # Blocks players from going below bedrock if they use an elytra.
    patch-vclip-exploit:
      # Modes: STRICT & ELYTRA
      # STRICT: Prevents players from going below bedrock
      # ELYTRA: Same as above, but only if they have an elytra equipped (Make sure your server has a decent anti-cheat, otherwise it can be bypassed!)
      mode: ELYTRA
      enable: true

# Miscellaneous
# Has support for the 'enable-spanish-translation' setting
misc:
  # Join events which include a motd and title message
  join-events:
    enable: true
    # Join motd, inspired by lsd2.org
    join-motd:
      first-join:
        en: "Welcome to the server!"
        es: "¡Bienvenido al servidor!"
      general:
        en: "Welcome back to the server!"
        es: "¡Bienvenido devuelta al servidor!"
    # Join title
    join-title-message:
      # You can disable this by setting everything to ""
      # This also applies to the action bar
      en: "Welcome"
      es: "Bienvenido"
    # Join action bar
    join-action-bar-message:
      en: "Welcome"
      es: "Bienvenido"
  # Simple announcements system, create as many as you want
  # Selection is purely random and repeated announcements can appear again.
  announcements:
    enable: true
    # Time in seconds
    timer: 60
    messages:
      example:
        en: "<gold>Example."
        es: "<gold>Ejemplo."
      example-two:
        en: "<gold>Example two."
        es: "<gold>Ejemplo dos."
  # Emergent announcements system
  # Useful for emergent announcements like "Server is restarting soon" // "We are currently suffering x problem"
  emergent-announcements:
    # By default, this is not enabled
    enable: false
    # Time in seconds (should be shorter than normal announcement's timer)
    timer: 15
    messages:
      example:
        en: "<gold>The server is currently suffering a problem, so expect low performance."
        es: "<gold>El servidor está teniendo problemas, así que puede que haya bajo rendimiento."

# Do not touch.
config-version: 7