name: Toms3Core
version: '1.0b12a'
main: io.github.Cherryh4ck.toms3Core.Toms3Core
api-version: '1.21'
authors: [ Cherryh4ck ]
description: Core for anarchy servers
commands:
  tmcore:
    description: Toms3Core main command
    usage: /tmcore [option]
    permission: tmcore.main
  playtime:
    description: Shows the playtime of a player
    usage: /playtime [player]
    aliases: pt
  dupe:
    description: Joke command.
    usage: /dupe
  joindate:
    description: Shows player's joindate
    usage: /joindate
    aliases: jd
  lastseen:
    description: Shows player's last seen date
    usage: /lastseen
    aliases: ls
  vote:
    description: Vote redirection, no actual use
    usage: /vote
  seed:
    description: Joke command
    usage: /seed